mozilla/voicefill

extension/manifest.json
package.json

Add correct updateURL to add-on

---

docs/acceptance.md

add txp acceptance criteria

---

package.json

Overwrite the existing web-extension during 'npm run build'

---

extension/assets/icon-done.svg
extension/content.js
extension/main.css

fixes #61 
fixes #62 
fixes #63

close, reset, animation added

---

extension/content.js

Fix title attributes for Cancel and Submit

---

extension/content.js
extension/manifest.json

add yahoo search

---

extension/metrics.js

@andrenatal This blocks launch

fix silent metrics error

---

.eslintignore
.eslintrc.yml
.gitignore
extension/content.js
package.json

ESLint still fails, but that's a known issue (ref: #23).

Ignore vendor bodymovin.js from linting

---

docs/metrics.md
extension/content.js
extension/manifest.json
package.json

improve metrics recording

---

extension/content.js

Add ref=product to qsurvey link

---

extension/content.js
extension/manifest.json

Add Bing support (issue #155 )

Add Bing support

---

extension/content.js

Add start.duckduckgo.com (fixing issue #148 )

Add start.duckduckgo.com

---

extension/content.js

Pressing Esc while voice search is open should close the UI

---

extension/content.js

issue #168 User must be notified with correct error message in case of MicroPhone being switched off/Disabled

---

extension/content.js

issue #192 Display failure notification to the user when no data is returned from the server

---

extension/content.js

issue #141 Present the options list even if the score is > 0.9 but the difference between the best options is too small

---

extension/content.js

Handle when no hypothesis is returned

---

extension/background.js
extension/content.js
extension/manifest.json

Fixes https://github.com/mozilla/speaktome/issues/215

Starting from a browser action

---

extension/content.js

Disable page's icon when activated from the toolbar

---

extension/manifest.json

Fixing toolbar icons

---

extension/content.js

Fix escaping

---

extension/content.js

Add Product-Tag header.

---

CHANGELOG.md
extension/background.js
extension/options.html
extension/options.js

Add setting for default search provider.

---

.eslintignore
.gitignore
bin/postinstall.sh
extension/manifest.json
package.json

Move node modules into vendor directory.

---

.travis.yml
CHANGELOG.md
extension/content.js

Fix Bing support.

---

CHANGELOG.md
extension/content.js

Add tooltips to buttons.

---

CHANGELOG.md
extension/assets/icon-done-rtl.svg
extension/content.js
extension/main.css
extension/manifest.json

Fix element positioning on RTL pages.

---

CHANGELOG.md
extension/js/content.js

Fix issue where microphone button could become disabled.

---

extension/js/content.js
extension/manifest.json

Blur icon after hiding popup.

---

.eslintrc.yml
CHANGELOG.md
bin/postinstall.sh
extension/js/background.js
extension/js/content.js
extension/manifest.json
package.json

Switch to using speaktome-api.
